### ISSUE TITLE
[Feature] auto-detect Vault name

### ISSUE THREAD

**Issue by huyz** [HenryC-3/vscode-plugin-obsidian-code#2]
I have multiple vaults, so it would be useful if this extension detected that the file was inside a specific vault (perhaps going up the folder tree to find `.obsidian`) and then automatically using that as the Vault name.

**Comment by HenryC-3** [comment]
This feature is beyond my usage since my notes are organized in a single folder, and I don't use obsidian a lot.

Feel free to fork this project and then implement it yourself.

**Comment by huyz** [comment]
Sounds good. If I can do it quickly, I'll submit a PR.  Otherwise, I will close this issue

**Comment by HenryC-3** [comment]
Extension updated, now available in the marketplace.

Checkout [obsidian-code - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=HenryHeDiff.obsidian-code)

Appreciate your PR #3.
